tmp_azure_aks_cluster: &aks_cluster "ezads-aks-stg"
tmp_azure_resource_group: &resource_group "ezads-stg"
tmp_azure_environment: &app_environment "npd"
tmp_prom_connect: &prom_connect "10.6.188.92:9201"

serverFiles:
  alerting_rules.yml: {}
  recording_rules.yml: {}

  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml

    scrape_configs:
      !include prometheus.yaml
      !include kubernetes-apiservers.yaml
      !include kubernetes-nodes.yaml
      !include kubernetes-nodes-cadvisor.yaml
      !include kubernetes-service-endpoints.yaml
      !include kubernetes-service-endpoints-slow.yaml
      !include prometheus-pushgateway.yaml
      !include kubernetes-services.yaml
      !include kubernetes-pods.yaml
      !include kubernetes-pods-slow.yaml

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false